[package]
name = "sudoku_generator"
version = "0.1.0"
edition = "2021"
authors = ["SudokuVersus Team"]

[lib]
name = "sudoku_generator"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.34"
rand = "0.8"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
